import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
  faArrowLeft,
  faArrowRight,
  faSignOutAlt,
  faCheckCircle,
  faCheckSquare,
  faCircle,
  faTimesCircle,
  faChevronDown,
  faPlusSquare,
  faInfoCircle,
  faFileCsv,
  faFileDownload,
  faFileUpload,
  faTable,
  faMicroscope,
  faSortUp,
  faSortDown,
  faFilter,
  faSyncAlt,
  faPencilAlt,
  faTrashAlt,
  faDatabase,
  faEdit,
  faPlus,
  faSave,
  faTimes,
  faBan,
  faTrash,
  faPowerOff,
  faEye,
  faEyeSlash,
  faChevronLeft,
  faChevronRight,
  faEllipsisH,
  faBoxOpen,
  faSearch,
} from "@fortawesome/free-solid-svg-icons";
library.add(
  faArrowLeft,
  faArrowRight,
  faSignOutAlt,
  faCheckCircle,
  faCheckSquare,
  faCircle,
  faTimesCircle,
  faChevronDown,
  faPlusSquare,
  faInfoCircle,
  faFileCsv,
  faFileDownload,
  faFileUpload,
  faTable,
  faMicroscope,
  faSortUp,
  faSortDown,
  faFilter,
  faSyncAlt,
  faPencilAlt,
  faTrashAlt,
  faDatabase,
  faEdit,
  faPlus,
  faSave,
  faTimes,
  faBan,
  faTrash,
  faPowerOff,
  faEye,
  faEyeSlash,
  faChevronLeft,
  faChevronRight,
  faEllipsisH,
  faBoxOpen,
  faSearch
);
createApp(App)
  .use(router)
  .component("FontAwesomeIcon", FontAwesomeIcon)
  .mount("#app");
